version: '3'

services:
  mysql-standalone:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=rootx 
    - MYSQL_DATABASE=test 
    - MYSQL_USER=testuser 
    - MYSQL_PASSWORD=testuser@123
  springboot-docker-container:
   image: user-docker-container
   ports:
     - 8084:8080
   build:
     context: ./
     dockerfile: Dockerfile
   depends_on:
     - mysql-standalone    
 